[package]
name = "proc-opt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

authors = ["Jan Bronicki janbronicki@gmail.com"]


[dependencies]



[dev-dependencies]
