[tasks.fc]
dependencies = ["format", "build", "test", "doc"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

# [tasks.check_format]
# command

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.doc]
command = "cargo"
args = ["doc"]
dependencies = ["clean"]
