name: Build

on: [push]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        name: 🔨Build release
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain:
                    - stable
                    - beta
                    - nightly
        steps:
            - uses: actions/checkout@v2
            - name: 🔨Build release
            - run: rustup update ${{ matrix.toolchain }} && \
                   rustup default ${{ matrix.toolchain }}
            - run: cargo build --release --verbose

    package:
        name: 📦Check package generation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 📦Check package generation
              run: cargo package --verbose
